version: '3.5'

services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data,delegated
  redis:
    image: redis:4-alpine

  server:
    build: ./server
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - ./server:/typeracer-api
      - ./server/bundle_cache:/bundle:rw,delegated
      - ./server/node_cache:/typeracer-api/node_modules:rw,delegated
    depends_on:
      - db
      - redis
    ports:
      - "3001:3001"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=
      - REDIS_URL=redis://redis:6379/1

  client:
    build: ./client
    command: npm start
    volumes:
      - './client:/typeracer'
      - './client/node_modules:/typeracer/node_modules'
    depends_on:
      - server
    ports:
      - '3000:3000'